#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : xvidcore
Version  : 1.3.7
Release  : 1
URL      : https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz
Source0  : https://downloads.xvid.com/downloads/xvidcore-1.3.7.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: xvidcore-lib = %{version}-%{release}
Requires: xvidcore-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : nasm-bin
BuildRequires : yasm
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
1) Introduction
---------------
Xvid is a high performance and high quality MPEG-4 video de-/encoding
solution.

%package dev
Summary: dev components for the xvidcore package.
Group: Development
Requires: xvidcore-lib = %{version}-%{release}
Provides: xvidcore-devel = %{version}-%{release}
Requires: xvidcore = %{version}-%{release}

%description dev
dev components for the xvidcore package.


%package lib
Summary: lib components for the xvidcore package.
Group: Libraries
Requires: xvidcore-license = %{version}-%{release}

%description lib
lib components for the xvidcore package.


%package license
Summary: license components for the xvidcore package.
Group: Default

%description license
license components for the xvidcore package.


%prep
%setup -q -n xvidcore
cd %{_builddir}/xvidcore

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1693339402
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
pushd build/generic
%configure --disable-static
make  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1693339402
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/xvidcore
cp %{_builddir}/xvidcore/LICENSE %{buildroot}/usr/share/package-licenses/xvidcore/05237420b351bb5b6f4dfcb3a4ce20c1a12584ea || :
cp %{_builddir}/xvidcore/vfw/LICENSE %{buildroot}/usr/share/package-licenses/xvidcore/e64c9c36e85d2022a45a3d4cb0f196c01f216072 || :
pushd build/generic
%make_install
popd

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/xvid.h
/usr/lib64/libxvidcore.so

%files lib
%defattr(-,root,root,-)
/usr/lib64/libxvidcore.so.4
/usr/lib64/libxvidcore.so.4.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/xvidcore/05237420b351bb5b6f4dfcb3a4ce20c1a12584ea
/usr/share/package-licenses/xvidcore/e64c9c36e85d2022a45a3d4cb0f196c01f216072
